import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/global/header/header";
import { AppFooter } from "@/components/layout/app-footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} min-h-screen antialiased flex flex-col`}
      >
        <AppHeader />
        <main className="flex-1 pt-14">{children}</main>
        <AppFooter />
      </body>
    </html>
  );
}
